<a href="https://colab.research.google.com/github/Tonge-Shim/1/blob/master/rfe_used2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.svm import LinearSVC
from collections import Counter
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from pandas import DataFrame
from imblearn.over_sampling import SMOTE
warnings.filterwarnings(action='ignore')

sns.set()
%matplotlib inline

In [5]:
df= pd.read_csv('samp_cst_feat.csv')

In [6]:
df.head()

     cst_id_di   VAR002  VAR003   VAR004  ...   VAR224   VAR225   VAR226   VAR227
0  90000000089 -0.06610  0.5280 -0.13607  ...  0.02938  0.17105  0.12537  0.22197
1  90000000176 -0.09537  0.1347 -0.13541  ... -0.01107  0.12413  0.29702 -0.31717
2  90000000210 -0.01048  0.8360  0.37797  ... -0.06314 -0.17111 -0.32239  0.33962
3  90000000212  0.05194  0.7505  0.04611  ...  0.01587 -0.04022  0.31213 -0.00559
4  90000000213 -0.08536  0.3767 -0.12288  ... -0.04698  0.03581  0.22588 -0.34868

[5 rows x 227 columns]

In [7]:
dtype = pd.read_excel('variable_dtype.xlsx')

dtype_categ = dtype[(dtype['dType']=='categorical')]
dtype_numrc = dtype[(dtype['dType']=='numerical')]
categ_var = dtype_categ['Variable_Name']
numrc_var = dtype_numrc['Variable_Name']
categ_var = categ_var.values.tolist()#0,1
numrc_var = numrc_var.values.tolist()#소수

dtype

    Variable_Name      dType
0          VAR002  numerical
1          VAR003  numerical
2          VAR004  numerical
3          VAR005  numerical
4          VAR006  numerical
..            ...        ...
221        VAR223  numerical
222        VAR224  numerical
223        VAR225  numerical
224        VAR226  numerical
225        VAR227  numerical

[226 rows x 2 columns]

In [8]:
x=df.drop(categ_var, axis=1).drop(['cst_id_di'],axis=1)
train=pd.read_csv('samp_train.csv')
train
mrc_0= train[(train['MRC_ID_DI']!=0)]#not 0!!!
mrc_0=mrc_0.drop(['cst_id_di'],axis=1)
mrc_0.loc[1:10119]
mrc_0=mrc_0.loc[1:10119]
indexlist_mrc_0=mrc_0.index.tolist()

x=x.loc[indexlist_mrc_0]#1~10까지의 , 소수점feature들

y=mrc_0['MRC_ID_DI']

mrc_1=mrc_0[(mrc_0['MRC_ID_DI']==1)]
mrc_2=mrc_0[(mrc_0['MRC_ID_DI']==2)]
mrc_3=mrc_0[(mrc_0['MRC_ID_DI']==3)]
mrc_4=mrc_0[(mrc_0['MRC_ID_DI']==4)]
mrc_5=mrc_0[(mrc_0['MRC_ID_DI']==5)]
mrc_6=mrc_0[(mrc_0['MRC_ID_DI']==6)]
mrc_7=mrc_0[(mrc_0['MRC_ID_DI']==7)]
mrc_8=mrc_0[(mrc_0['MRC_ID_DI']==8)]
mrc_9=mrc_0[(mrc_0['MRC_ID_DI']==9)]
mrc_10=mrc_0[(mrc_0['MRC_ID_DI']==10)]

x_1=x.loc[mrc_1.index.tolist()]
x_2=x.loc[mrc_2.index.tolist()]
x_3=x.loc[mrc_3.index.tolist()]
x_4=x.loc[mrc_4.index.tolist()]
x_5=x.loc[mrc_5.index.tolist()]
x_6=x.loc[mrc_6.index.tolist()]
x_7=x.loc[mrc_7.index.tolist()]
x_8=x.loc[mrc_8.index.tolist()]
x_9=x.loc[mrc_9.index.tolist()]
x_10=x.loc[mrc_10.index.tolist()]

In [9]:
mrc_0['MRC_ID_DI'].value_counts()

7     661
6     554
8     337
5     143
1      85
9      59
3      32
10     28
2      14
4      11
Name: MRC_ID_DI, dtype: int64

In [10]:
x
mrc_0

#mrc=pd.DataFrame({'Column1': y_resampled})
#mrc['Column1'].value_counts()

       MRC_ID_DI
1              8
3              5
4              6
10             8
15             8
...          ...
10100          7
10108          7
10110          7
10117          6
10119          7

[1924 rows x 1 columns]

In [11]:

print(x.shape)
print(y.shape)

#y=mrc_0['MRC_ID_DI']

(1924, 198)
(1924,)

In [12]:
logreg=LogisticRegression()
selector=RFE(logreg)
selector=selector.fit(x,y)#99등까지의 것을 다시 selector 함수에 대입

In [13]:
selected_features=DataFrame({'Feature': list(x.columns), 'Ranking': selector.ranking_})
selected_features.sort_values(by='Ranking').head(50)

    Feature  Ranking
197  VAR227        1
88   VAR105        1
87   VAR104        1
86   VAR103        1
85   VAR102        1
84   VAR101        1
164  VAR192        1
81   VAR095        1
79   VAR092        1
77   VAR090        1
166  VAR194        1
167  VAR195        1
90   VAR108        1
73   VAR086        1
71   VAR084        1
70   VAR083        1
169  VAR197        1
68   VAR081        1
67   VAR080        1
132  VAR157        1
65   VAR076        1
63   VAR074        1
62   VAR073        1
61   VAR072        1
60   VAR069        1
72   VAR085        1
92   VAR110        1
93   VAR112        1
161  VAR189        1
131  VAR156        1
136  VAR161        1
129  VAR154        1
128  VAR153        1
127  VAR152        1
138  VAR163        1
124  VAR149        1
123  VAR147        1
122  VAR146        1
140  VAR166        1
117  VAR138        1
115  VAR136        1
143  VAR169        1
112  VAR133        1
149  VAR175        1
108  VAR129        1
107  VAR128        1
155  VAR183        1
157  VAR185        1
101  VAR120        1
158  VAR186        1

In [14]:
newx=selected_features.sort_values(by='Ranking')['Feature']
newx=newx.loc[197:40]#ranking2ndround
newx.tolist()
X=x[newx]

print(X.shape)
print(y.shape)
X
X

(1924, 99)
(1924,)

        VAR227  VAR105   VAR104  VAR103  ...   VAR206   VAR207   VAR209   VAR046
1     -0.31717  0.0064  0.11679  0.2265  ...  0.09975  0.22539  0.09554 -0.18782
3     -0.00559  0.4801  0.10292  0.2017  ... -0.09442 -0.17412 -0.38673 -0.17060
4     -0.34868  0.0094  0.19224  0.7221  ...  0.07929  0.10444  0.26548 -0.11939
10    -0.03924  0.3992  0.21952  0.3791  ...  0.05307  0.07087  0.12910 -0.17447
15    -0.17489  0.0051  0.04123  0.2140  ... -0.06258 -0.07324 -0.31118 -0.15740
...        ...     ...      ...     ...  ...      ...      ...      ...      ...
10100  0.20226  0.4795  0.32646  0.5887  ... -0.01301 -0.03573  0.15902 -0.09630
10108 -0.32806  0.0010  0.28819  0.8929  ...  0.11533  0.14114  0.37351 -0.12668
10110  0.06141  1.0000  0.19925  0.4090  ...  0.04059  0.14631  0.03864 -0.14550
10117 -0.11591  0.3518  0.12561  0.4316  ... -0.00193 -0.02627  0.05273 -0.21469
10119 -0.25995  0.4997  0.24620  0.3077  ...  0.00081 -0.02277 -0.08027 -0.26872

[1924 rows x 99 columns]

In [15]:
sm = SMOTE(ratio='auto', kind='regular')
X_re, y_re = sm.fit_sample(X,y)

In [16]:
X_train, X_test, Y_train, Y_test=train_test_split(X_re,y_re,random_state=30)#99feature, 6610samples
x_train, x_test, y_train, y_test=train_test_split(X,y, random_state=30)#99feature, 1924 samples
#print(X_train.shape)
print(x_test.shape)
print(x_train.shape)
#print(y_train.shape)
#print(y_test.shape)

(481, 99)
(1443, 99)

In [17]:
logreg=LogisticRegression()
y_pred=logreg.fit(X_train,Y_train).predict(x_test)
print('The Accuracy of the model is {:.1f}%'.format(accuracy_score(y_test,y_pred)*100))

The Accuracy of the model is 38.7%